exclude_paths:
  - tmp
  - vendor

detectors:
  LongParameterList:
    enabled: false
  ModuleInitialize:
    exclude:
      - Milestoner::Models
  TooManyStatements:
    exclude:
      - Milestoner::CLI::Shell#cli
  UnusedParameters:
    exclude:
      - Milestoner::Renderers::Universal#call
