exclude_paths:
  - tmp
  - vendor

detectors:
  ControlParameter:
    exclude:
      - Milestoner::CLI::Actions::Publish#call
      - Milestoner::Tags::Creator#compute_version
      - Milestoner::Tags::Pusher#compute_version
  LongParameterList:
    enabled: false
  ModuleInitialize:
    exclude:
      - Milestoner::Models
  NestedIterators:
    exclude:
      - Milestoner::Commits::Versioner#trailer_milestones
  TooManyMethods:
    exclude:
      - Milestoner::Views::Parts::Commit
  TooManyStatements:
    exclude:
      - Milestoner::CLI::Shell#cli
  UnusedParameters:
    exclude:
      - Milestoner::Renderers::Universal#call
