# frozen_string_literal: true

require "dry/monads"
require "spec_helper"

RSpec.describe Milestoner::Builders::ASCIIDoc do
  include Dry::Monads[:result]

  using Refinements::Pathname

  subject(:builder) { described_class.new tagger: }

  include_context "with application dependencies"
  include_context "with enriched tag"

  let(:tagger) { instance_double Milestoner::Commits::Tagger, call: Success(tags) }

  describe "#call" do
    let(:content) { path.read }
    let(:path) { temp_dir.join "index.adoc" }

    context "with single tag" do
      before { settings.build_max = 1 }

      it "includes logo, label, version, and date" do
        settings.project_uri_logo = "https://acme.io/logo.png"

        builder.call

        expect(content).to include(
          "= pass:[ ]image:https://acme.io/logo.png[Logo,50,50]pass:[ ]" \
          "link:https://undefined.io/projects/test[Test] 0.0.0 (2024-07-04)"
        )
      end

      it "doesn't include logo when not present" do
        settings.project_uri_logo = nil
        builder.call

        expect(content).not_to match(/logo.png/)
      end

      it "renders owner" do
        builder.call

        expect(content).to include(
          "image:https://avatars.githubusercontent.com/u/1[Malcolm Reynolds,24,24] " \
          "link:https://github.com/mal[Malcolm Reynolds]"
        )
      end

      it "doesn't render owner when tags have no commits" do
        tags.each { |tag| tag.commits.clear }
        builder.call

        expect(content).not_to include("Malcolm Reynolds")
      end

      it "renders secure when signature exists" do
        builder.call
        expect(content).to include("🔒 Tag (secure)")
      end

      it "renders insecure when signature doesn't exist" do
        tag.signature = nil
        builder.call

        expect(content).to include("🔓 Tag (insecure)")
      end

      it "renders commit summary" do
        builder.call

        expect(content).to include(
          ".🟢 Added documentation - link:https://github.com/zoe[Zoe Washburne]"
        )
      end

      it "renders commit message" do
        builder.call

        expect(content).to include(<<~CONTENT)
          [%collapsible]
          ====
          *Message*

          None.
        CONTENT
      end

      it "renders notes" do
        builder.call

        expect(content).to include(<<~CONTENT)
          *Notes*

          None.
        CONTENT
      end

      it "renders commit author" do
        builder.call

        expect(content).to include(<<~CONTENT)
          *Author*

          image:https://avatars.githubusercontent.com/u/1[Zoe Washburne,24,24] link:https://github.com/zoe[Zoe Washburne]
        CONTENT
      end

      it "renders collaborators" do
        builder.call

        expect(content).to include(<<~CONTENT)
          *Collaborators*

          * image:https://avatars.githubusercontent.com/u/2[River Tam,24,24] link:https://github.com/river[River Tam]
        CONTENT
      end

      it "renders signers" do
        builder.call

        expect(content).to include(<<~CONTENT)
          *Signers*

          * image:https://avatars.githubusercontent.com/u/3[Malcolm Renolds,24,24] link:https://github.com/mal[Malcolm Renolds]
        CONTENT
      end

      it "renders details" do
        builder.call

        expect(content).to include(<<~CONTENT)
          *Details*

          * Milestone: Patch
          * Signature: Good
          * Files: link:https://source.firefly.com/serenity/commit/180dec7d8ae8[2]
          * Lines: -10/+5
          * Issue: link:https://issue.firefly.com/123[123]
          * Review: link:https://review.firefly.com/456[999]
        CONTENT
      end

      it "renders commit date/time" do
        builder.call
        expect(content).to include("_2023-01-01 (Sunday) 10:10 AM MST_")
      end

      it "renders commits stats" do
        builder.call
        expect(content).to include("*1 commit. 2 files. 10 deletions. 5 insertions.*")
      end

      it "renders generator" do
        builder.call

        expect(content).to include(
          "_Generated by link:https://alchemists.io/projects/milestoner[Milestoner 3.2.1]._"
        )
      end

      it "renders zero stats with no commits" do
        allow(tagger).to receive(:call).and_return(
          Success([Milestoner::Models::Tag[commits: [], version: "0.0.0"]])
        )

        builder.call

        expect(content).to include("*0 commits. 0 files. 0 deletions. 0 insertions.*")
      end

      it "builds custom path" do
        settings.build_basename = "test"
        builder.call

        expect(temp_dir.join("test.adoc").exist?).to be(true)
      end

      it "logs path when success" do
        builder.call
        expect(logger.reread).to match(/🟢.+Built: #{path}\./)
      end

      it "answers build root when success" do
        expect(builder.call).to eq(Success(temp_dir))
      end
    end

    context "with multiple tags" do
      before { settings.build_max = 2 }

      it "builds versioned indexes" do
        builder.call

        expect(temp_dir.files("**/*")).to contain_exactly(
          temp_dir.join("0.0.0/index.adoc"),
          temp_dir.join("0.1.0/index.adoc")
        )
      end

      it "logs paths" do
        builder.call

        expect(logger.reread).to match(
          /
           🟢.+Built:\s#{temp_dir.join "0.1.0/index.adoc"}\..+
           🟢.+Built:\s#{temp_dir.join "0.0.0/index.adoc"}\.
          /mx
        )
      end

      it "answers root path when success" do
        expect(builder.call).to eq(Success(temp_dir))
      end
    end

    context "with failure" do
      before { allow(tagger).to receive(:call).and_return(Failure("Danger!")) }

      it "logs error" do
        builder.call
        expect(logger.reread).to match(/🛑.+Danger!/)
      end

      it "answers message" do
        expect(builder.call).to eq(Failure("Danger!"))
      end
    end
  end
end
