# frozen_string_literal: true

require "dry/monads"
require "spec_helper"

RSpec.describe Milestoner::Builders::Markdown do
  include Dry::Monads[:result]

  using Refinements::Pathname

  subject(:builder) { described_class.new tagger: }

  include_context "with application dependencies"
  include_context "with enriched tag"

  let(:tagger) { instance_double Milestoner::Commits::Tagger, call: Success(tags) }

  describe "#call" do
    let(:content) { path.read }
    let(:path) { temp_dir.join "index.md" }

    context "with single tag" do
      before { settings.build_max = 1 }

      it "includes logo when present" do
        builder.call

        expect(content).to include(
          %(<img src="https://undefined.io/assets/media/projects/milestoner/logo.png" ) +
          %(alt="Logo" width="100" height="100">)
        )
      end

      it "doesn't include logo when not present" do
        settings.project_uri_logo = nil
        builder.call

        expect(content).not_to match(/logo.png/)
      end

      it "includes label and version" do
        builder.call

        expect(content).to include("# [Test](https://undefined.io/projects/milestoner) 1.2.3")
      end

      it "includes date" do
        builder.call
        expect(content).to match(/\(\d{4}-\d{2}-\d{2}\)/)
      end

      it "renders owner" do
        builder.call

        expect(content).to include(
          %(<img src="https://avatars.githubusercontent.com/u/1" alt="Malcolm Reynolds" ) +
          %(width="24" height="24" loading="lazy"> ) +
          "[Malcolm Reynolds](https://github.com/mal)"
        )
      end

      it "doesn't render owner when tags have no commits" do
        tags.each { |tag| tag.commits.clear }
        builder.call

        expect(content).not_to include("Malcolm Reynolds")
      end

      it "renders valid when signature exists" do
        builder.call
        expect(content).to include("🔒 Tag (valid)")
      end

      it "renders invalid when signature doesn't exist" do
        tag.signature = nil
        builder.call

        expect(content).to include("🔓 Tag (invalid)")
      end

      it "renders content" do
        builder.call

        expect(content).to include(<<~BODY)
          - 🟢 Added documentation - [Zoe Washburne](https://github.com/zoe)

          **1 commit. 2 files. 10 deletions. 5 insertions.**
        BODY
      end

      it "includes generator" do
        builder.call

        expect(content).to include(
          "*Generated by [Milestoner 3.2.1](https://alchemists.io/projects/milestoner).*"
        )
      end

      it "renders zero stats with no commits" do
        allow(tagger).to receive(:call).and_return(
          Success([Milestoner::Models::Tag[commits: [], version: "0.0.0"]])
        )

        builder.call

        expect(content).to include("*0 commits. 0 files. 0 deletions. 0 insertions.*")
      end

      it "builds custom path" do
        settings.build_basename = "test"
        builder.call

        expect(temp_dir.join("test.md").exist?).to be(true)
      end

      it "logs path when success" do
        builder.call
        expect(logger.reread).to match(/🟢.+Built: #{path}\./)
      end

      it "answers build root when success" do
        expect(builder.call).to eq(Success(temp_dir))
      end
    end

    context "with multiple tags" do
      before { settings.build_max = 2 }

      it "builds versioned indexes" do
        builder.call

        expect(temp_dir.files("**/*")).to contain_exactly(
          temp_dir.join("0.0.0/index.md"),
          temp_dir.join("0.1.0/index.md")
        )
      end

      it "logs paths" do
        builder.call

        expect(logger.reread).to match(
          /
           🟢.+Built:\s#{temp_dir.join "0.1.0/index.md"}\..+
           🟢.+Built:\s#{temp_dir.join "0.0.0/index.md"}\.
          /mx
        )
      end

      it "answers root path when success" do
        expect(builder.call).to eq(Success(temp_dir))
      end
    end

    context "with failure" do
      before { allow(tagger).to receive(:call).and_return(Failure("Danger!")) }

      it "logs error" do
        builder.call
        expect(logger.reread).to match(/🛑.+Danger!/)
      end

      it "answers message" do
        expect(builder.call).to eq(Failure("Danger!"))
      end
    end
  end
end
