# frozen_string_literal: true

require "dry/monads"
require "spec_helper"
require "versionaire"

RSpec.describe Milestoner::Builders::Stream do
  include Dry::Monads[:result]

  using Refinements::Pathname
  using Refinements::StringIO
  using Refinements::Struct
  using Versionaire::Cast

  subject(:builder) { described_class.new tagger: }

  include_context "with application dependencies"
  include_context "with enriched tag"

  let(:tagger) { instance_double Milestoner::Commits::Tagger, call: Success(tags) }

  describe "#call" do
    context "with single tag" do
      let :proof do
        <<~CONTENT
          Test 0.1.0 (2024-07-05)

          Malcolm Reynolds | 🔒 Tag (valid)

          🟢 Added documentation - Zoe Washburne

          1 commit. 2 files. 10 deletions. 5 insertions.

          Generated by Milestoner 3.2.1.
        CONTENT
      end

      before { tags.pop }

      it "renders content" do
        builder.call
        expect(io.reread).to eq(proof)
      end

      it "answers content when success" do
        builder.call
        expect(builder.call).to eq(Success(proof))
      end
    end

    context "with multiple tag" do
      let :proof do
        <<~CONTENT
          Test 0.1.0 (2024-07-05)

          Malcolm Reynolds | 🔒 Tag (valid)

          🟢 Added documentation - Zoe Washburne

          1 commit. 2 files. 10 deletions. 5 insertions.

          Generated by Milestoner 3.2.1.


          Test 0.0.0 (2024-07-04)

          Malcolm Reynolds | 🔒 Tag (valid)

          🟢 Added documentation - Zoe Washburne

          1 commit. 2 files. 10 deletions. 5 insertions.

          Generated by Milestoner 3.2.1.
        CONTENT
      end

      it "renders content" do
        builder.call
        expect(io.reread).to eq(proof)
      end

      it "answers content when success" do
        expect(builder.call).to eq(Success(proof))
      end
    end

    context "with identical tag" do
      before do
        tags.pop
        tags.first.merge! version: Version("1.2.3")
      end

      it "renders content" do
        builder.call

        expect(io.reread).to eq(<<~CONTENT)
          Test 1.2.3 (2024-07-05)

          🟢 Added documentation - Zoe Washburne

          1 commit. 2 files. 10 deletions. 5 insertions.

          Generated by Milestoner 3.2.1.
        CONTENT
      end
    end

    context "without commits" do
      let :tags do
        [
          Milestoner::Models::Tag[
            commits: [],
            version: "0.0.0",
            committed_at: Time.local(2024, 7, 1)
          ]
        ]
      end

      it "renders no commits with zero stats" do
        builder.call

        expect(io.reread).to eq(<<~CONTENT)
          Test (2024-07-01)

          0 commits. 0 files. 0 deletions. 0 insertions.

          Generated by Milestoner 3.2.1.
        CONTENT
      end
    end

    context "with failure" do
      before { allow(tagger).to receive(:call).and_return(Failure("Danger!")) }

      it "logs error" do
        builder.call
        expect(logger.reread).to match(/🛑.+Danger!/)
      end

      it "answers message" do
        expect(builder.call).to eq(Failure("Danger!"))
      end
    end
  end
end
