# frozen_string_literal: true

require "dry/monads"
require "spec_helper"

RSpec.describe Milestoner::Builders::Web do
  include Dry::Monads[:result]

  using Refinements::Pathname

  subject(:builder) { described_class.new enricher: }

  include_context "with application dependencies"
  include_context "with enriched commit"

  let(:enricher) { instance_double Milestoner::Commits::Enricher, call: Success([commit]) }

  describe "#call" do
    let(:html_path) { temp_dir.join "index.html" }

    it "builds HTML and CSS" do
      builder.call
      expect(temp_dir.files).to contain_exactly(html_path, temp_dir.join("page.css"))
    end

    it "includes title" do
      builder.call
      expect(html_path.read).to include(%(<title>Test Label 1.2.3</title>))
                            .or include(%(<title>Milestoner))
    end

    it "includes description meta" do
      builder.call
      expect(html_path.read).to include(%(<meta name="description" content="Test description.">))
                            .or include(%(<meta name="description" content="A))
    end

    it "includes author meta" do
      builder.call
      expect(html_path.read).to include(%(<meta name="author" content="Test Author">))
                            .or include(%(<meta name="author" content="Test User">))
                            .or include(%(<meta name="author" content="B))
    end

    it "includes generator meta" do
      builder.call
      expect(html_path.read).to include(%(<meta name="generator" content="Test Generator">))
                            .or include(%(<meta name="generator" content="Milestoner))
    end

    it "includes generator link" do
      builder.call
      primary = %(Generated by <a href="https://test.com" class="link">Test Generator</a>)

      expect(html_path.read).to include(primary)
                            .or include(%(Generated by <a href="https://alchemists.io))
    end

    it "answers build path" do
      expect(builder.call).to eq(temp_dir)
    end
  end
end
