# frozen_string_literal: true

require "dry/monads"
require "spec_helper"

RSpec.describe Milestoner::Builders::Web do
  include Dry::Monads[:result]

  using Refinements::Pathname

  subject(:builder) { described_class.new enricher: }

  include_context "with application dependencies"
  include_context "with enriched commit"

  let(:enricher) { instance_double Milestoner::Commits::Enricher, call: Success([commit]) }

  describe "#call" do
    let(:html_path) { temp_dir.join "index.html" }

    it "builds default HTML and CSS" do
      builder.call
      expect(temp_dir.files).to contain_exactly(html_path, temp_dir.join("page.css"))
    end

    it "builds custom HTML and CSS" do
      settings.build_basename = "test"
      settings.build_stylesheet = "test"
      builder.call

      expect(temp_dir.files).to contain_exactly(
        temp_dir.join("test.html"),
        temp_dir.join("test.css")
      )
    end

    it "ignores relative path when building CSS file" do
      settings.build_stylesheet = "../page"
      builder.call

      expect(temp_dir.files).to contain_exactly(
        temp_dir.join("index.html"),
        temp_dir.join("page.css")
      )
    end

    it "builds only HTML when stylesheet is disabled" do
      settings.build_stylesheet = false
      builder.call

      expect(temp_dir.files).to contain_exactly(html_path)
    end

    it "includes title" do
      builder.call
      expect(html_path.read).to include("<title>Test 1.2.3</title>")
    end

    it "includes description meta" do
      builder.call
      expect(html_path.read).to include(%(<meta name="description" content="A test.">))
    end

    it "includes author meta" do
      builder.call
      expect(html_path.read).to include(%(<meta name="author" content="Tester">))
    end

    it "includes generator meta" do
      builder.call
      expect(html_path.read).to include(%(<meta name="generator" content="Milestoner 3.2.1">))
    end

    it "includes stylesheet when enabled" do
      builder.call
      expect(html_path.read).to include(%(href="page.css"))
    end

    it "excludes stylesheet when disabled" do
      settings.build_stylesheet = false
      builder.call

      expect(html_path.read).not_to include(%(rel="stylesheet"))
    end

    it "includes logo when present" do
      builder.call

      expect(html_path.read).to include(
        %(<img src="https://undefined.io/assets/media/projects/milestoner/logo.png" ) +
        %(alt="Logo" width="30" height="30">)
      )
    end

    it "doesn't include logo when not present" do
      settings.project_uri_logo = nil
      builder.call

      expect(html_path.read).not_to include(
        %(<img src="https://undefined.io/assets/media/projects/milestoner/logo.png" ) +
        %(alt="Logo" width="30" height="30">)
      )
    end

    it "includes generator link" do
      builder.call
      url = "https://alchemists.io/projects/milestoner"

      expect(html_path.read).to include(
        %(Generated by <a href="#{url}" class="link">Milestoner 3.2.1</a>)
      )
    end

    it "answers build path" do
      expect(builder.call).to eq(temp_dir)
    end
  end
end
