# frozen_string_literal: true

require "dry/monads"
require "spec_helper"

RSpec.describe Milestoner::Builders::Web do
  include Dry::Monads[:result]

  using Refinements::Pathname

  subject(:builder) { described_class.new enricher: }

  include_context "with application dependencies"
  include_context "with enriched commit"

  let(:enricher) { instance_double Milestoner::Commits::Enricher, call: Success([commit]) }

  describe "#call" do
    let(:html_path) { temp_dir.join "index.html" }

    it "builds HTML and CSS" do
      builder.call
      expect(temp_dir.files).to contain_exactly(html_path, temp_dir.join("page.css"))
    end

    it "includes title" do
      builder.call
      expect(html_path.read).to include("<title>Test 1.2.3</title>")
    end

    it "includes description meta" do
      builder.call
      expect(html_path.read).to include(%(<meta name="description" content="A test.">))
    end

    it "includes author meta" do
      builder.call
      expect(html_path.read).to include(%(<meta name="author" content="Tester">))
    end

    it "includes generator meta" do
      builder.call
      expect(html_path.read).to include(%(<meta name="generator" content="Milestoner 3.2.1">))
    end

    it "includes generator link" do
      builder.call
      url = "https://alchemists.io/projects/milestoner"

      expect(html_path.read).to include(
        %(Generated by <a href="#{url}" class="link">Milestoner 3.2.1</a>)
      )
    end

    it "answers build path" do
      expect(builder.call).to eq(temp_dir)
    end
  end
end
