# frozen_string_literal: true

require "spec_helper"

RSpec.describe Milestoner::Builders::ADoc::Indexer do
  subject(:builder) { described_class.new }

  include_context "with application dependencies"
  include_context "with enriched tag"

  describe "#call" do
    let(:path) { temp_dir.join "index.adoc" }

    it "includes title" do
      builder.call tags
      expect(path.read).to include("== link:https://undefined.io/projects/test[Test] Versions")
    end

    it "builds file with tags" do
      builder.call tags

      expect(path.read).to include(<<~CONTENT)
        * link:/0.1.0/[0.1.0] (2024-07-05)
        * link:/0.0.0/[0.0.0] (2024-07-04)
      CONTENT
    end

    it "builds file without tags" do
      builder.call []

      expect(path.read).not_to include(<<~CONTENT)
        * link:/0.1.0/[0.1.0] (2024-07-05)
        * link:/0.0.0/[0.0.0] (2024-07-04)
      CONTENT
    end

    it "includes generator" do
      builder.call tags

      expect(path.read).to include(
        "_Generated by link:https://alchemists.io/projects/milestoner[Milestoner 3.2.1]._"
      )
    end

    it "answers path" do
      expect(builder.call(tags)).to be_success(path)
    end
  end
end
