inherit_gem:
  caliber: config/all.yml

Metrics/BlockLength:
  AllowedPatterns:
    - register
Metrics/CollectionLiteralLength:
  Exclude:
    - "spec/support/shared_contexts/enriched_commit.rb"
    - "spec/lib/milestoner/builders/stream_spec.rb"
