# frozen_string_literal: true

require "dry/monads"
require "spec_helper"

RSpec.describe Milestoner::Builders::Site::Indexer do
  include Dry::Monads[:result]

  using Refinements::Pathname

  subject(:builder) { described_class.new }

  include_context "with application dependencies"
  include_context "with enriched tag"

  describe "#call" do
    let(:path) { temp_dir.join "index.html" }
    let(:tags_pattern) { %r(<li.+0\.1\.0.+0\.0\.0.+</li>)m }

    it "includes title without version" do
      builder.call tags
      expect(path.read).to include(%(<title>Test | Undefined</title>))
    end

    it "includes label" do
      builder.call tags

      expect(path.read).to include(
        %(<a href="https://undefined.io/projects/test" class="label">Test</a> Versions)
      )
    end

    it "builds file with tags" do
      builder.call tags
      expect(path.read).to match(tags_pattern)
    end

    it "builds file without tags" do
      builder.call []
      expect(path.read).not_to match(tags_pattern)
    end

    it "includes generator" do
      builder.call tags

      expect(path.read).to include(
        %(Generated by <a href="https://alchemists.io/projects/milestoner">Milestoner 3.2.1</a>)
      )
    end

    it "answers path" do
      expect(builder.call(tags)).to eq(Success(path))
    end

    context "when disabled" do
      before { settings.build_index = false }

      it "answers empty array" do
        builder.call tags
        expect(temp_dir.files("**/*")).to eq([])
      end

      it "answers empty success" do
        expect(builder.call(tags)).to eq(Success())
      end
    end
  end
end
