# frozen_string_literal: true

require "dry/monads"
require "spec_helper"

RSpec.describe Milestoner::Builders::MD::Indexer do
  include Dry::Monads[:result]

  subject(:builder) { described_class.new }

  include_context "with application dependencies"
  include_context "with enriched tag"

  describe "#call" do
    let(:path) { temp_dir.join "index.md" }

    it "includes title" do
      builder.call tags
      expect(path.read).to include("# [Test](https://undefined.io/projects/test) Versions")
    end

    it "builds file with tags" do
      builder.call tags

      expect(path.read).to include(<<~CONTENT)
        - [0.1.0](0.1.0) (2024-07-05)
        - [0.0.0](0.0.0) (2024-07-04)
      CONTENT
    end

    it "builds file without tags" do
      builder.call []

      expect(path.read).not_to include(<<~CONTENT)
        - [0.1.0](0.1.0) (2024-07-05)
        - [0.0.0](0.0.0) (2024-07-04)
      CONTENT
    end

    it "includes generator" do
      builder.call tags

      expect(path.read).to include(
        "*Generated by [Milestoner 3.2.1](https://alchemists.io/projects/milestoner)."
      )
    end

    it "answers path" do
      expect(builder.call(tags)).to eq(Success(path))
    end
  end
end
