# frozen_string_literal: true

require "dry/monads"
require "spec_helper"

RSpec.describe Milestoner::Builders::MD::Pager do
  include Dry::Monads[:result]

  using Refinements::Struct

  subject(:builder) { described_class.new }

  include_context "with application dependencies"
  include_context "with enriched tag"

  let(:tagger) { instance_double Milestoner::Commits::Tagger, call: Success(tags) }

  describe "#call" do
    let(:path) { temp_dir.join "0.1.0/index.md" }
    let(:past) { tag.with version: "0.0.0" }
    let(:present) { tag.with version: "0.1.0" }
    let(:future) { tag.with version: "1.0.0" }

    it "includes logo when present" do
      settings.project_uri_logo = "https://acme.io/icon.png"
      builder.call past, present, future

      expect(path.read).to include(
        %(<img src="https://acme.io/icon.png" alt="Logo" width="100" height="100">)
      )
    end

    it "doesn't include logo when not present" do
      settings.project_uri_logo = nil
      builder.call past, present, future

      expect(path.read).not_to match(/logo.png/)
    end

    it "includes label, version, and date" do
      builder.call past, present, future

      expect(path.read).to include(
        "# [Test](https://undefined.io/projects/test) 0.1.0 (2024-07-04)"
      )
    end

    it "renders owner" do
      builder.call past, present, future

      expect(path.read).to include(
        %(<img src="https://avatars.githubusercontent.com/u/1" alt="Malcolm Reynolds" ) +
        %(width="24" height="24" loading="lazy"> [Malcolm Reynolds](https://github.com/mal))
      )
    end

    it "doesn't render owner when tags have no commits" do
      tags.each { |tag| tag.commits.clear }
      builder.call past, present, future

      expect(path.read).not_to include("Malcolm Reynolds")
    end

    it "renders secure when signature exists" do
      builder.call past, present, future
      expect(path.read).to include("🔒 Tag (secure)")
    end

    it "renders insecure when signature doesn't exist" do
      tag.signature = nil
      builder.call past, present, future

      expect(path.read).to include("🔓 Tag (insecure)")
    end

    it "renders content" do
      builder.call past, present, future

      expect(path.read).to include(<<~BODY)
        - 🟢 Added documentation - [Zoe Washburne](https://github.com/zoe)

        **1 commit. 2 files. 10 deletions. 5 insertions.**
      BODY
    end

    it "renders totals" do
      builder.call past, present, future

      expect(path.read).to include <<~CONTENT
        **1 commit. 2 files. 10 deletions. 5 insertions.**
        **5 hours, 5 minutes, and 5 seconds.**
      CONTENT
    end

    it "renders zero totals with no commits" do
      present = Milestoner::Models::Tag[commits: [], version: "0.1.0"]

      builder.call past, present, future

      expect(path.read).to include <<~CONTENT
        **0 commits. 0 files. 0 deletions. 0 insertions.**
        **0 seconds.**
      CONTENT
    end

    it "includes generator" do
      builder.call past, present, future

      expect(path.read).to include(
        "*Generated by [Milestoner 3.2.1](https://alchemists.io/projects/milestoner).*"
      )
    end

    it "renders previous and next links" do
      builder.call past, present, future
      expect(path.read).to include("[Previous (0.0.0)](0.0.0) | [Next (1.0.0)](1.0.0)")
    end

    it "answers file path" do
      expect(builder.call(past, present, future)).to eq(Success(path))
    end
  end
end
